// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Returns the status of the API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health healthz"
                ],
                "summary": "Check API health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/views.HealthzResponse"
                        }
                    }
                }
            }
        },
        "/sheets/movies": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "movies"
                ],
                "summary": "Handle HTTP request for retrieving list of movies from Google Sheets (specified by local spreadsheetID).",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MovieMeta"
                            }
                        }
                    }
                }
            }
        },
        "/sheets/movies/{tmdbID}/poster": {
            "get": {
                "produces": [
                    "image/jpeg"
                ],
                "tags": [
                    "movies"
                ],
                "summary": "Handle HTTP request for retrieving a movie poster from TMDB (specified by TMDB ID).",
                "responses": {
                    "200": {
                        "description": "movie poster",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.MovieMeta": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "posterURL": {
                    "type": "string"
                },
                "suggestedBy": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "tmdbid": {
                    "type": "string"
                },
                "watched": {
                    "type": "boolean"
                }
            }
        },
        "views.HealthzResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Bad Movie Spinner API",
	Description:      "Backend API for communication with Google Sheets list of movies and TMDB",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
