basePath: /
definitions:
  handlers.HealthzResponse:
    properties:
      status:
        example: ok
        type: string
    type: object
  models.MovieMeta:
    properties:
      description:
        type: string
      posterURL:
        type: string
      suggestedBy:
        type: string
      title:
        type: string
      tmdbid:
        type: string
      watched:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: Backend API for communication with Google Sheets list of movies and
    TMDB
  title: Bad Movie Spinner API
  version: "1.0"
paths:
  /healthz:
    get:
      description: Returns the status of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HealthzResponse'
      summary: Check API health
      tags:
      - health healthz
  /sheets/movies:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.MovieMeta'
            type: array
      summary: Handle HTTP request for retrieving list of movies from Google Sheets
        (specified by local spreadsheetID).
      tags:
      - movies
swagger: "2.0"
